
package micro.csvagraficas.UI;

import micro.csvagraficas.control.ControlArchivo;
import micro.csvagraficas.control.Grafica;


public class VistaPrincipal extends javax.swing.JFrame {


    public VistaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAbrirCSV = new javax.swing.JButton();
        jButtonDT = new javax.swing.JButton();
        jButtonVT = new javax.swing.JButton();
        jButtonAT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jButtonAbrirCSV.setBackground(new java.awt.Color(20, 140, 115));
        jButtonAbrirCSV.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAbrirCSV.setText("Seleccionar Archivo");
        jButtonAbrirCSV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAbrirCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirCSVActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAbrirCSV);

        jButtonDT.setBackground(new java.awt.Color(20, 160, 130));
        jButtonDT.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDT.setText("Distancia vs. Tiempo");
        jButtonDT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDTActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDT);

        jButtonVT.setBackground(new java.awt.Color(70, 180, 160));
        jButtonVT.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVT.setText("Velocidad vs. Tiempo");
        jButtonVT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVTActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVT);

        jButtonAT.setBackground(new java.awt.Color(120, 200, 180));
        jButtonAT.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAT.setText("Aceleración vs. Tiempo");
        jButtonAT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAT);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 180));

        jLabel1.setBackground(new java.awt.Color(40, 40, 40));
        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(200, 230, 210));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><br><center><h2>CINEMATICA <br>CON ARDUINO</h2></html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirCSVActionPerformed
        ControlArchivo.abrirArchivo(this);
        this.setTitle(ControlArchivo.archivo.getName());
    }//GEN-LAST:event_jButtonAbrirCSVActionPerformed

    private void jButtonDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDTActionPerformed
        Grafica grafica = new Grafica(ControlArchivo.getLanzamientos());
        grafica.crearGrafica(Grafica.DISTANCIA_TIEMPO);
//        grafica.exportar(chart);
    }//GEN-LAST:event_jButtonDTActionPerformed

    private void jButtonVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVTActionPerformed
        Grafica grafica = new Grafica(ControlArchivo.getLanzamientos());
        grafica.crearGrafica(Grafica.VELOCIDAD_TIEMPO);
    }//GEN-LAST:event_jButtonVTActionPerformed

    private void jButtonATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATActionPerformed
        Grafica grafica = new Grafica(ControlArchivo.getLanzamientos());
        grafica.crearGrafica(Grafica.ACELERACION_TIEMPO);
    }//GEN-LAST:event_jButtonATActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAT;
    private javax.swing.JButton jButtonAbrirCSV;
    private javax.swing.JButton jButtonDT;
    private javax.swing.JButton jButtonVT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
