
package micro.csvagraficas.UI;


public class Vista extends javax.swing.JFrame {

    /** Creates new form Vista */
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotonesFail = new javax.swing.JPanel();
        jButtonDTfail = new javax.swing.JButton();
        jButtonVTfail = new javax.swing.JButton();
        jButtonATfail = new javax.swing.JButton();
        jPanelFondo = new javax.swing.JPanel();
        jPanelLadoI = new javax.swing.JPanel();
        jPanelLadoD = new javax.swing.JPanel();
        jPanelEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelBotones = new javax.swing.JPanel();
        jButtonDT = new javax.swing.JButton();
        jButtonVT = new javax.swing.JButton();
        jButtonAT = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCargar = new javax.swing.JMenu();

        jButtonDTfail.setText("Distancia vs. Tiempo");
        jPanelBotonesFail.add(jButtonDTfail);

        jButtonVTfail.setText("Velocidad vs. Tiempo");
        jPanelBotonesFail.add(jButtonVTfail);

        jButtonATfail.setText("Aceleración vs. Tiempo");
        jPanelBotonesFail.add(jButtonATfail);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(102, 102, 102));
        jPanelFondo.setLayout(new java.awt.BorderLayout());

        jPanelLadoI.setOpaque(false);

        javax.swing.GroupLayout jPanelLadoILayout = new javax.swing.GroupLayout(jPanelLadoI);
        jPanelLadoI.setLayout(jPanelLadoILayout);
        jPanelLadoILayout.setHorizontalGroup(
            jPanelLadoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelLadoILayout.setVerticalGroup(
            jPanelLadoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanelLadoI, java.awt.BorderLayout.LINE_START);

        jPanelLadoD.setOpaque(false);

        javax.swing.GroupLayout jPanelLadoDLayout = new javax.swing.GroupLayout(jPanelLadoD);
        jPanelLadoD.setLayout(jPanelLadoDLayout);
        jPanelLadoDLayout.setHorizontalGroup(
            jPanelLadoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelLadoDLayout.setVerticalGroup(
            jPanelLadoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanelLadoD, java.awt.BorderLayout.LINE_END);

        jPanelEncabezado.setOpaque(false);

        jLabel1.setText("Resultados: ");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanelEncabezadoLayout = new javax.swing.GroupLayout(jPanelEncabezado);
        jPanelEncabezado.setLayout(jPanelEncabezadoLayout);
        jPanelEncabezadoLayout.setHorizontalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEncabezadoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(310, 310, 310))
        );
        jPanelEncabezadoLayout.setVerticalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24))
        );

        jPanelFondo.add(jPanelEncabezado, java.awt.BorderLayout.PAGE_START);

        jPanelTabla.setLayout(new java.awt.GridLayout(1, 0));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanelTabla.add(jScrollPane2);

        jPanelFondo.add(jPanelTabla, java.awt.BorderLayout.CENTER);

        jPanelBotones.setMinimumSize(new java.awt.Dimension(452, 60));
        jPanelBotones.setOpaque(false);

        jButtonDT.setText("Distancia vs. Tiempo");
        jPanelBotones.add(jButtonDT);

        jButtonVT.setText("Velocidad vs. Tiempo");
        jPanelBotones.add(jButtonVT);

        jButtonAT.setText("Aceleracion vs. Tiempo");
        jPanelBotones.add(jButtonAT);

        jPanelFondo.add(jPanelBotones, java.awt.BorderLayout.PAGE_END);

        jMenuCargar.setText("Cargar Archivo");
        jMenuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCargarActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuCargar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAT;
    private javax.swing.JButton jButtonATfail;
    private javax.swing.JButton jButtonDT;
    private javax.swing.JButton jButtonDTfail;
    private javax.swing.JButton jButtonVT;
    private javax.swing.JButton jButtonVTfail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCargar;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelBotonesFail;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelLadoD;
    private javax.swing.JPanel jPanelLadoI;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
